# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  test-3_7-django2_2-ariadne: &test-template
    parameters:
      django_version:
        type: string
        default: "2.2"
      library:
        type: string
        default: "ariadne"
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/<< parameters.library >>.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]
            pip install psycopg2
      - run:
          name: install django version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install django==<< parameters.django_version >>
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/<< parameters.library >>.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            DJANGO_SETTINGS_MODULE=test_settings/<< parameters.library >> pytest
            coveralls
      - store_artifacts:
          path: test-reports
          destination: test-reports

#  test-3_8-django2_2:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.8-rc-stretch
#  test-3_8-django1_11:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.8-rc-stretch
#  test-3_7-django3:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.7-stretch
#  test-3_7-django2_2:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.7-stretch
#  test-3_7-django1_11:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.7-stretch
#  test-3_6-django3:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.6-jessie
  test-3_6-django2_2-ariadne:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
  test-3_6-django2_2-django-graphql:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
#  test-3_6-django1_11:
#    <<: *test-template
#    docker:
#      - image: circleci/python:3.6-jessie

workflows:
  version: 2
  test:
    jobs:
#      - test-3_7-django3:
#          django_version: "3"
      - test-3_7-django2_2-ariadne:
          django_version: "2.2"
          library: "ariadne"
#      - test-3_7-django1_11:
#          django_version: "1.11"
#      - test-3_6-django3:
#          django_version: "3"
      - test-3_6-django2_2-ariadne:
          django_version: "2.2"
          library: "ariadne"
      - test-3_6-django2_2-django-graphql:
          django_version: "2.2"
          library: "django-graphql"
#      - test-3_6-django1_11:
#          django_version: "1.11"
